### ISSUE TITLE
Channel 모듈 리팩토링 

### ISSUE THREAD

**Issue by sbsny** [ft-transcendence-seoul/backend#20]
[Feature/#1-channel-모듈-구현] branch에 push 완료

기존 controller에 있던 메소드 이외에 inviteUser, join 메소드 추가.

✔invite API는 
@Post(':channel_id/invite/:user_id') // 뒤에 user_id 필요.
// adminguard
  inviteUser(
    @GetUser() requestingUser: User,
    @Param('channel_id', ChannelByIdPipe) channel: Channel,
    @Param('user_id', UserByIdPipe) invitedUser: User,
    ) {
    return this.channelService.inviteUser(channel, invitedUser, requestingUser);
  }
-> Kick과 Ban 기능과 마찬가지로 뒤에 /:user_id가 필요합니다. 노션에는 /channels/{channel_id}/invite 이렇게만 정의됨.
Kick과 Ban 예시 [@Post(':channel_id/ban/:user_id')] invite도 이와 동일. 

✔@Post(':channel_id')
  join(@GetUser() user: User, @Param('channel_id', ParseIntPipe) channelId: number) {
    return this.channelService.join(user, channelId);
  }
컨트롤러의 join 메소드에서 password를 어떤 식으로 받아야 될지 상의 필요.

< ㅡㅡㅡㅡ 남은 과제 ㅡㅡㅡㅡ>
1. 우진님이 계획 중인 transaction, mute, guard 구현
2. 방금 전 push한 코드를 좀 더 보완하고 일요일 회의 때까지 service와 chatgateway 소켓과의 병합

남은 과제 이외에 빠진 부분이나 수정할 사항 있으면 comment주세요!

**Comment by izone00** [comment]
kick, ban, invite는 말씀대로 추가하면 될것같고
코드 pr도 올려주세요
